---
- name: Configure daemon
  script: "scripts/registry.py --registry {{ ansible_default_ipv4.address }}:{{ registry_port }}"

- name: Restart docker
  service:  
    name: docker
    state: restarted
    
- name: Create root directory
  file:
    patch: "{{ storage_root_directory }}"
    state: directory

- name: Create data directory
  file:
    patch: "{{ storage_root_directory }}/data"
    state: directory

- name: Post config
  template: templates/config_http.yml.j2
  dest: "{{ storage_root_directory }}/config_http.yml"

- name: Start docker container
  docker_container:
    image: "{{ docker_registry_container }}"
    restart_policy: always
    state: started
    name: registry
    volumes: 
      - "{{ storage_root_directory }}/config_http.yml:/etc/docker/registry/config.yml"
      - "{{ storage_root_directory }}/data:/var/lib/registry"

